spring:
  datasource:
    url: jdbc:h2:file:~/card-cost-db;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS "public"\;SET SCHEMA "public"
    username: sa
    password: sa
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

card-cost:
  binlist:
    baseUrl: https://lookup.binlist.net