CREATE TABLE "countries" (
    "alpha2" CHAR(2) PRIMARY KEY,
    "alpha3" CHAR(3) UNIQUE,
    "numeric" CHAR(3) UNIQUE,
    "name" VARCHAR(64) NOT NULL,
    "clearing_cost_usd" NUMERIC(6, 2) NOT NULL,
    "version" BIGINT NOT NULL DEFAULT 1
);

INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('AF', 'AFG', '004', 'Afghanistan', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('AX', 'ALA', '248', 'Åland Islands', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('AL', 'ALB', '008', 'Albania', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('DZ', 'DZA', '012', 'Algeria', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('AS', 'ASM', '016', 'American Samoa', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('AD', 'AND', '020', 'Andorra', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('AO', 'AGO', '024', 'Angola', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('AI', 'AIA', '660', 'Anguilla', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('AQ', 'ATA', '010', 'Antarctica', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('AG', 'ATG', '028', 'Antigua and Barbuda', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('AR', 'ARG', '032', 'Argentina', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('AM', 'ARM', '051', 'Armenia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('AW', 'ABW', '533', 'Aruba', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('AU', 'AUS', '036', 'Australia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('AT', 'AUT', '040', 'Austria', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('AZ', 'AZE', '031', 'Azerbaijan', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('BS', 'BHS', '044', 'Bahamas', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('BH', 'BHR', '048', 'Bahrain', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('BD', 'BGD', '050', 'Bangladesh', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('BB', 'BRB', '052', 'Barbados', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('BY', 'BLR', '112', 'Belarus', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('BE', 'BEL', '056', 'Belgium', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('BZ', 'BLZ', '084', 'Belize', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('BJ', 'BEN', '204', 'Benin', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('BM', 'BMU', '060', 'Bermuda', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('BT', 'BTN', '064', 'Bhutan', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('BO', 'BOL', '068', 'Bolivia (Plurinational State of)', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('BQ', 'BES', '535', 'Bonaire, Sint Eustatius and Saba', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('BA', 'BIH', '070', 'Bosnia and Herzegovina', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('BW', 'BWA', '072', 'Botswana', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('BV', 'BVT', '074', 'Bouvet Island', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('BR', 'BRA', '076', 'Brazil', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('IO', 'IOT', '086', 'British Indian Ocean Territory', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('BN', 'BRN', '096', 'Brunei Darussalam', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('BG', 'BGR', '100', 'Bulgaria', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('BF', 'BFA', '854', 'Burkina Faso', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('BI', 'BDI', '108', 'Burundi', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('CV', 'CPV', '132', 'Cabo Verde', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('KH', 'KHM', '116', 'Cambodia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('CM', 'CMR', '120', 'Cameroon', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('CA', 'CAN', '124', 'Canada', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('KY', 'CYM', '136', 'Cayman Islands', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('CF', 'CAF', '140', 'Central African Republic', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('TD', 'TCD', '148', 'Chad', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('CL', 'CHL', '152', 'Chile', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('CN', 'CHN', '156', 'China', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('CX', 'CXR', '162', 'Christmas Island', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('CC', 'CCK', '166', 'Cocos (Keeling) Islands', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('CO', 'COL', '170', 'Colombia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('KM', 'COM', '174', 'Comoros', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('CG', 'COG', '178', 'Congo', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('CD', 'COD', '180', 'Congo (Democratic Republic of the)', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('CK', 'COK', '184', 'Cook Islands', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('CR', 'CRI', '188', 'Costa Rica', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('CI', 'CIV', '384', 'Côte d''Ivoire', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('HR', 'HRV', '191', 'Croatia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('CU', 'CUB', '192', 'Cuba', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('CW', 'CUW', '531', 'Curaçao', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('CY', 'CYP', '196', 'Cyprus', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('CZ', 'CZE', '203', 'Czechia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('DK', 'DNK', '208', 'Denmark', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('DJ', 'DJI', '262', 'Djibouti', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('DM', 'DMA', '212', 'Dominica', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('DO', 'DOM', '214', 'Dominican Republic', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('EC', 'ECU', '218', 'Ecuador', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('EG', 'EGY', '818', 'Egypt', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('SV', 'SLV', '222', 'El Salvador', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('GQ', 'GNQ', '226', 'Equatorial Guinea', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('ER', 'ERI', '232', 'Eritrea', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('EE', 'EST', '233', 'Estonia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('ET', 'ETH', '231', 'Ethiopia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('FK', 'FLK', '238', 'Falkland Islands (Malvinas)', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('FO', 'FRO', '234', 'Faroe Islands', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('FJ', 'FJI', '242', 'Fiji', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('FI', 'FIN', '246', 'Finland', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('FR', 'FRA', '250', 'France', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('GF', 'GUF', '254', 'French Guiana', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('PF', 'PYF', '258', 'French Polynesia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('TF', 'ATF', '260', 'French Southern Territories', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('GA', 'GAB', '266', 'Gabon', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('GM', 'GMB', '270', 'Gambia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('GE', 'GEO', '268', 'Georgia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('DE', 'DEU', '276', 'Germany', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('GH', 'GHA', '288', 'Ghana', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('GI', 'GIB', '292', 'Gibraltar', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('GR', 'GRC', '300', 'Greece', 15.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('GL', 'GRL', '304', 'Greenland', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('GD', 'GRD', '308', 'Grenada', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('GP', 'GLP', '312', 'Guadeloupe', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('GU', 'GUM', '316', 'Guam', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('GT', 'GTM', '320', 'Guatemala', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('GG', 'GGY', '831', 'Guernsey', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('GN', 'GIN', '324', 'Guinea', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('GW', 'GNB', '624', 'Guinea-Bissau', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('GY', 'GUY', '328', 'Guyana', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('HT', 'HTI', '332', 'Haiti', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('HM', 'HMD', '334', 'Heard Island and McDonald Islands', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('VA', 'VAT', '336', 'Holy See', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('HN', 'HND', '340', 'Honduras', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('HK', 'HKG', '344', 'Hong Kong', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('HU', 'HUN', '348', 'Hungary', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('IS', 'ISL', '352', 'Iceland', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('IN', 'IND', '356', 'India', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('ID', 'IDN', '360', 'Indonesia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('IR', 'IRN', '364', 'Iran (Islamic Republic of)', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('IQ', 'IRQ', '368', 'Iraq', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('IE', 'IRL', '372', 'Ireland', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('IM', 'IMN', '833', 'Isle of Man', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('IL', 'ISR', '376', 'Israel', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('IT', 'ITA', '380', 'Italy', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('JM', 'JAM', '388', 'Jamaica', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('JP', 'JPN', '392', 'Japan', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('JE', 'JEY', '832', 'Jersey', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('JO', 'JOR', '400', 'Jordan', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('KZ', 'KAZ', '398', 'Kazakhstan', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('KE', 'KEN', '404', 'Kenya', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('KI', 'KIR', '296', 'Kiribati', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('KP', 'PRK', '408', 'Korea (Democratic People''s Republic of)', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('KR', 'KOR', '410', 'Korea (Republic of)', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('KW', 'KWT', '414', 'Kuwait', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('KG', 'KGZ', '417', 'Kyrgyzstan', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('LA', 'LAO', '418', 'Lao People''s Democratic Republic', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('LV', 'LVA', '428', 'Latvia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('LB', 'LBN', '422', 'Lebanon', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('LS', 'LSO', '426', 'Lesotho', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('LR', 'LBR', '430', 'Liberia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('LY', 'LBY', '434', 'Libya', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('LI', 'LIE', '438', 'Liechtenstein', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('LT', 'LTU', '440', 'Lithuania', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('LU', 'LUX', '442', 'Luxembourg', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('MO', 'MAC', '446', 'Macao', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('MK', 'MKD', '807', 'North Macedonia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('MG', 'MDG', '450', 'Madagascar', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('MW', 'MWI', '454', 'Malawi', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('MY', 'MYS', '458', 'Malaysia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('MV', 'MDV', '462', 'Maldives', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('ML', 'MLI', '466', 'Mali', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('MT', 'MLT', '470', 'Malta', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('MH', 'MHL', '584', 'Marshall Islands', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('MQ', 'MTQ', '474', 'Martinique', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('MR', 'MRT', '478', 'Mauritania', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('MU', 'MUS', '480', 'Mauritius', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('YT', 'MYT', '175', 'Mayotte', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('MX', 'MEX', '484', 'Mexico', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('FM', 'FSM', '583', 'Micronesia (Federated States of)', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('MD', 'MDA', '498', 'Moldova (Republic of)', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('MC', 'MCO', '492', 'Monaco', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('MN', 'MNG', '496', 'Mongolia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('ME', 'MNE', '499', 'Montenegro', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('MS', 'MSR', '500', 'Montserrat', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('MA', 'MAR', '504', 'Morocco', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('MZ', 'MOZ', '508', 'Mozambique', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('MM', 'MMR', '104', 'Myanmar', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('NA', 'NAM', '516', 'Namibia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('NR', 'NRU', '520', 'Nauru', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('NP', 'NPL', '524', 'Nepal', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('NL', 'NLD', '528', 'Netherlands', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('NC', 'NCL', '540', 'New Caledonia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('NZ', 'NZL', '554', 'New Zealand', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('NI', 'NIC', '558', 'Nicaragua', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('NE', 'NER', '562', 'Niger', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('NG', 'NGA', '566', 'Nigeria', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('NU', 'NIU', '570', 'Niue', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('NF', 'NFK', '574', 'Norfolk Island', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('MP', 'MNP', '580', 'Northern Mariana Islands', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('NO', 'NOR', '578', 'Norway', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('OM', 'OMN', '512', 'Oman', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('PK', 'PAK', '586', 'Pakistan', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('PW', 'PLW', '585', 'Palau', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('PS', 'PSE', '275', 'Palestine, State of', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('PA', 'PAN', '591', 'Panama', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('PG', 'PNG', '598', 'Papua New Guinea', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('PY', 'PRY', '600', 'Paraguay', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('PE', 'PER', '604', 'Peru', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('PH', 'PHL', '608', 'Philippines', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('PN', 'PCN', '612', 'Pitcairn', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('PL', 'POL', '616', 'Poland', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('PT', 'PRT', '620', 'Portugal', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('PR', 'PRI', '630', 'Puerto Rico', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('QA', 'QAT', '634', 'Qatar', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('RE', 'REU', '638', 'Réunion', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('RO', 'ROU', '642', 'Romania', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('RU', 'RUS', '643', 'Russian Federation', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('RW', 'RWA', '646', 'Rwanda', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('BL', 'BLM', '652', 'Saint Barthélemy', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('SH', 'SHN', '654', 'Saint Helena, Ascension and Tristan da Cunha', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('KN', 'KNA', '659', 'Saint Kitts and Nevis', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('LC', 'LCA', '662', 'Saint Lucia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('MF', 'MAF', '663', 'Saint Martin (French part)', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('PM', 'SPM', '666', 'Saint Pierre and Miquelon', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('VC', 'VCT', '670', 'Saint Vincent and the Grenadines', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('WS', 'WSM', '882', 'Samoa', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('SM', 'SMR', '674', 'San Marino', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('ST', 'STP', '678', 'Sao Tome and Principe', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('SA', 'SAU', '682', 'Saudi Arabia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('SN', 'SEN', '686', 'Senegal', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('RS', 'SRB', '688', 'Serbia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('SC', 'SYC', '690', 'Seychelles', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('SL', 'SLE', '694', 'Sierra Leone', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('SG', 'SGP', '702', 'Singapore', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('SX', 'SXM', '534', 'Sint Maarten (Dutch part)', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('SK', 'SVK', '703', 'Slovakia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('SI', 'SVN', '705', 'Slovenia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('SB', 'SLB', '090', 'Solomon Islands', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('SO', 'SOM', '706', 'Somalia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('ZA', 'ZAF', '710', 'South Africa', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('GS', 'SGS', '239', 'South Georgia and the South Sandwich Islands', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('SS', 'SSD', '728', 'South Sudan', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('ES', 'ESP', '724', 'Spain', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('LK', 'LKA', '144', 'Sri Lanka', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('SD', 'SDN', '729', 'Sudan', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('SR', 'SUR', '740', 'Suriname', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('SJ', 'SJM', '744', 'Svalbard and Jan Mayen', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('SZ', 'SWZ', '748', 'Eswatini', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('SE', 'SWE', '752', 'Sweden', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('CH', 'CHE', '756', 'Switzerland', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('SY', 'SYR', '760', 'Syrian Arab Republic', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('TW', 'TWN', '158', 'Taiwan, Province of China[a]', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('TJ', 'TJK', '762', 'Tajikistan', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('TZ', 'TZA', '834', 'Tanzania, United Republic of', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('TH', 'THA', '764', 'Thailand', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('TL', 'TLS', '626', 'Timor-Leste', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('TG', 'TGO', '768', 'Togo', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('TK', 'TKL', '772', 'Tokelau', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('TO', 'TON', '776', 'Tonga', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('TT', 'TTO', '780', 'Trinidad and Tobago', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('TN', 'TUN', '788', 'Tunisia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('TR', 'TUR', '792', 'Turkey', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('TM', 'TKM', '795', 'Turkmenistan', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('TC', 'TCA', '796', 'Turks and Caicos Islands', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('TV', 'TUV', '798', 'Tuvalu', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('UG', 'UGA', '800', 'Uganda', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('UA', 'UKR', '804', 'Ukraine', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('AE', 'ARE', '784', 'United Arab Emirates', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('GB', 'GBR', '826', 'United Kingdom of Great Britain and Northern Ireland', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('US', 'USA', '840', 'United States of America', 5.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('UM', 'UMI', '581', 'United States Minor Outlying Islands', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('UY', 'URY', '858', 'Uruguay', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('UZ', 'UZB', '860', 'Uzbekistan', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('VU', 'VUT', '548', 'Vanuatu', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('VE', 'VEN', '862', 'Venezuela (Bolivarian Republic of)', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('VN', 'VNM', '704', 'Viet Nam', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('VG', 'VGB', '092', 'Virgin Islands (British)', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('VI', 'VIR', '850', 'Virgin Islands (U.S.)', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('WF', 'WLF', '876', 'Wallis and Futuna', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('EH', 'ESH', '732', 'Western Sahara', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('YE', 'YEM', '887', 'Yemen', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('ZM', 'ZMB', '894', 'Zambia', 10.0);
INSERT INTO "countries" ("alpha2", "alpha3", "numeric", "name", "clearing_cost_usd") VALUES ('ZW', 'ZWE', '716', 'Zimbabwe', 10.0);
